### ISSUE TITLE
[Feature] Improving Preloader

### ISSUE THREAD

**Issue by VidhanThakur09** [swaraj-das/Collect-your-GamingTools#194]
### Current Behaviour

The current Loading has no preloader. The screen becomes blank when the website loads.

### Proposed Solution

Enhancing the preloader, and improving the styling of the preloader design would greatly improve the user experience and website presentation

### Tasks:

- Redesign the preloader for better visual appeal.
- Improving the preloader.

@swaraj-das  can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

### Screenshot/Mockup

https://github.com/user-attachments/assets/88c859b3-2864-49a7-b8d6-b9d9025455f5

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by VidhanThakur09** [comment]
Hello PA, can you please add label for levels according to the issue ....
